add support for BOOTIF kernel arg used with PXE
The BOOTIF kernel arg typically used with PXE boot specifies
the MAC address of the Ethernet adapter used on the system
where the OS will be booted from.

Change-Id: I7ccf209a239372e96536d14c7a3a9dd189979ef6
Reviewed-on: https://git-master.nvidia.com/r/c/tinylinux/source/+/3101914
Reviewed-by: Keyur Patel <keyurap@nvidia.com>
Tested-by: Chris Dragan <kdragan@nvidia.com>
Reviewed-by: Chris Dragan <kdragan@nvidia.com>

diff --git a/linuxrc b/linuxrc
--- a/linuxrc
+++ b/linuxrc
@@ -14,6 +14,7 @@ MNTETC="mnt/etc"
 SQUASHFS_BIN="tiny/squash.bin"
 NFSSHARE=""
 NET="eth0"
+MAC=""
 OVRCFG="1"
 READONLY=""
 COLDPLUG="1"
@@ -55,6 +56,7 @@ for ARG in $(cat /proc/cmdline); do
         partno\=*)        PARTNUMBER="${ARG#*=}" ;;
         nfsshare\=*)      NFSSHARE="${ARG#*=}" ;;
         net\=*)           NET="${ARG#*=}" ;;
+        BOOTIF\=*)        MAC="${ARG#*=}" ;;
         ovrcfg\=*)        OVRCFG="${ARG#*=}" ;;
         mount_timeout\=*) MNT_TIMEOUT="${ARG#*=}" ;;
         nocoldplug)       COLDPLUG="" ;;
@@ -92,6 +94,34 @@ mount_squash()
     fi
 }
 
+find_net_dev_from_mac()
+{
+    # Skip if BOOTIF was not specified
+    [ -n "$MAC" ] || return 0
+
+    # Turn requested MAC address to lowercase
+    MAC=$(echo "$MAC" | tr '[A-Z]' '[a-z]')
+
+    local LOOP=0
+    while true; do
+        local IIFACE
+        for IIFACE in $(ls /sys/class/net); do
+            [ -f "/sys/class/net/$IIFACE/address" ] || continue
+            local CURMAC=$(cat "/sys/class/net/$IIFACE/address" | tr '[A-Z]' '[a-z]')
+            if [ "$CURMAC" = "$MAC" ]; then
+                NET="$IIFACE"
+                echo "Found network interface $NET with MAC address $MAC"
+                return 0
+            fi
+        done
+        [ $LOOP -eq 1 ] && echo "Waiting for network interface with MAC address $MAC"
+        LOOP=$(($LOOP + 1))
+        local WAITTIME=$(($(awk '{print $1*1000}' /proc/uptime) - $KERNEL_BOOT_TIME))
+        [ $WAITTIME -gt $((MNT_TIMEOUT * 1000)) ] && break
+    done
+    echo "Network interface with MAC address $MAC not found!"
+}
+
 # Mount non-volatile volume or NFS share
 mkdir -p "${ROOTFS}/${MNTNV}" "${ROOTFS}/${MNTSQUASH}"
 RETRYCOUNT=0
@@ -99,6 +129,7 @@ TRIEDDEVS=""
 FOUNDDEV=""
 while true; do
     if [ "$NFSSHARE" ]; then
+        find_net_dev_from_mac
         if [ -e "/sys/class/net/$NET" ]; then
             echo "Obtaining DHCP lease for $NET..."
             FOUNDDEV="$NET"
diff --git a/scripts/etc/init.d/net b/scripts/etc/init.d/net
--- a/scripts/etc/init.d/net
+++ b/scripts/etc/init.d/net
@@ -21,6 +21,7 @@ for ARG in `cat /proc/cmdline`; do
         dns\=*) DNS="${ARG#*=}" ; DNS="${DNS//,/ }" ;;
         dnsdomain\=*) DNSDOMAIN="${ARG#*=}" ;;
         nfsshare\=*) IFACE="none" ;; # DHCP already done
+        BOOTIF\=*) IFACEMAC=$(echo "${ARG#*=}" | tr '[A-Z]' '[a-z]') ;;
     esac
 done
 
@@ -69,8 +70,37 @@ bring_down_ifaces()
     done
 }
 
+get_iface_from_mac()
+{
+    local IFACEMAC="$1"
+    local LOOP=0
+    while [ $LOOP -lt $((TIMEOUT * 2)) ]; do
+        local IIFACE
+        for IIFACE in $(ls /sys/class/net); do
+            [ -f "/sys/class/net/$IIFACE/address" ] || continue
+            local CURMAC=$(cat "/sys/class/net/$IIFACE/address" | tr '[A-Z]' '[a-z]')
+            if [ "$CURMAC" = "$IFACEMAC" ]; then
+                IFACE="$IIFACE"
+                return 0
+            fi
+        done
+        [ -e "/sys/class/net/$IFACE" ] && break
+        LOOP=$((LOOP + 1))
+        info "waiting for $IFACEMAC"
+        sleep 0.5
+    done
+    return 1
+}
+
 start()
 {
+    TIMEOUT=${TIMEOUT:-1}
+
+    if [ -n "${IFACEMAC:-}" ] && ! get_iface_from_mac "$IFACEMAC"; then
+        error "interface not found"
+        return 1
+    fi
+
     if [ $IFACE = "auto" ]; then
         local LOOP=0
         local FOUND_IFACES
@@ -143,14 +173,8 @@ start()
 
     local NUM_IFACES=$(echo "$IFACE" | wc -w)
 
-    # Fail if interface explicitly requested by user does not exist
-    if [ $NUM_IFACES -eq 1 ] && [ ! -d "/sys/class/net/$IFACE" ]; then
-        info "missing $IFACE"
-        return 1
-    fi
-
     # Wait for the network interface if it does not exist
-    if [ $NUM_IFACES -eq 1 -a ! -d "/sys/class/net/$IFACE" -a -n "$TIMEOUT" ]; then
+    if [ $NUM_IFACES -eq 1 ] && [ ! -d "/sys/class/net/$IFACE" ]; then
         info "waiting for $IFACE"
         local LOOP=0
         while [ $LOOP -lt $((TIMEOUT * 2)) ]; do
@@ -159,6 +183,12 @@ start()
             sleep 0.5
             echo -n "." >&3
         done
+    fi
+
+    # Fail if interface explicitly requested by user does not exist
+    if [ $NUM_IFACES -eq 1 ] && [ ! -d "/sys/class/net/$IFACE" ]; then
+        info "missing $IFACE"
+        return 1
     fi
 
     # Bring up networking
