add start/stop/restart/zap in /sbin/rc
Change-Id: I03fcff01fb6ddc6c449a4ba696bcbfc94512b973
Reviewed-on: https://git-master.nvidia.com/r/2274476
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Lael Jones <lajones@nvidia.com>
Reviewed-by: Chris Dragan <kdragan@nvidia.com>
Tested-by: Chris Dragan <kdragan@nvidia.com>

diff --git a/scripts/sbin/rc b/scripts/sbin/rc
--- a/scripts/sbin/rc
+++ b/scripts/sbin/rc
@@ -312,6 +312,26 @@ elif [ "$1" = "disable" ]; then
     # Prevent losing data during accidental reboot
     sync
 
+# Start/stop/restart/zap services
+elif [ "$1" = "start" ] || [ "$1" = "stop" ] || [ "$1" = "restart" ] || [ "$1" = "zap" ]; then
+
+    ACTION="$1"
+    shift
+    while [ $# -gt 0 ]; do
+
+        # Check if such service exists
+        if [ ! -f "/etc/init.d/$1" ]; then
+            echo "Service $1 not found!"
+            exit 1
+        fi
+
+        # Attempt to stop the service
+        /etc/init.d/$1 "$ACTION"
+
+        # Next service
+        shift
+    done
+
 # System init
 elif [ "$1" = "sysinit" ]; then
 
