configure DHCP on multiple interfaces
Change-Id: I894037d624b00b13796de7e779ba5b0f1c12fcd4
Reviewed-on: https://git-master.nvidia.com/r/c/tinylinux/source/+/2937884
Reviewed-by: Lael Jones <lajones@nvidia.com>
Reviewed-by: Keyur Patel <keyurap@nvidia.com>
Reviewed-by: Chris Dragan <kdragan@nvidia.com>
Tested-by: Chris Dragan <kdragan@nvidia.com>

diff --git a/scripts/etc/init.d/net b/scripts/etc/init.d/net
--- a/scripts/etc/init.d/net
+++ b/scripts/etc/init.d/net
@@ -38,12 +38,31 @@ setup_wlan()
     WIRELESS_UP="$1"
 }
 
+has_carrier()
+{
+    [ -f "/sys/class/net/$1/carrier" ] || return 1
+    local CARRIER=$(cat "/sys/class/net/$1/carrier" 2>/dev/null || true)
+    [ "$CARRIER" = "1" ]
+}
+
 bring_down_ifaces()
 {
-    local IIFACE
+    [ -n "$1" ] || return 0
+
     # Bring down all the interfaces brought up
+    local IIFACE
     for IIFACE in $1; do
-        if [ "$IIFACE" != "$2" ]; then
+        local BRING_DOWN=1
+        if [ -n "$2" ]; then
+            local JIFACE
+            for JIFACE in $2; do
+                if [ "$IIFACE" == "$2" ]; then
+                    BRING_DOWN=""
+                    break
+                fi
+            done
+        fi
+        if [ -n "$BRING_DOWN" ]; then
             ifconfig "$IIFACE" down
         fi
     done
@@ -53,14 +72,18 @@ start()
 {
     if [ $IFACE = "auto" ]; then
         local LOOP=0
-        local FOUND_IFACE
+        local FOUND_IFACES
+        local CARRIER_IFACES
         local IFACES_BROUGHT_UP
         while [ $LOOP -lt $((TIMEOUT * 2)) ]; do
+            FOUND_IFACES=""
+            CARRIER_IFACES=""
             local IIFACE
             for IIFACE in $(ls /sys/class/net); do
                 [ "$IIFACE" != 'lo' ] || continue
                 setup_wlan "$IIFACE"
                 [ -f "/sys/class/net/$IIFACE/carrier" ] || continue
+                FOUND_IFACES="$FOUND_IFACES $IIFACE"
                 local IFACELINKSTATUS
                 IFACELINKSTATUS=$(cat "/sys/class/net/$IIFACE/carrier" 2>/dev/null)
                 if [ $? = 1 ]; then
@@ -72,21 +95,23 @@ start()
                         [ $LOOP -le 2 ] || LOOP=2
                     fi
                 elif [ "$IFACELINKSTATUS" = 1 ]; then
-                    # If the interface was already brought up by linuxrc, use it
+                    # If the interface was already brought up by somebody, use it
                     if ifconfig "$IIFACE" | grep -q "inet addr"; then
-                        echo "$IIFACE" > "$SAVED_IFACE_FILE"
                         bring_down_ifaces "$IFACES_BROUGHT_UP" "$IIFACE"
+                        info "reusing $IIFACE"
+                        echo "$IIFACE" > "$SAVED_IFACE_FILE"
                         return 0
                     fi
 
-                    FOUND_IFACE="$IIFACE"
-                    info "auto-detected $FOUND_IFACE"
-                    break
+                    CARRIER_IFACES="$CARRIER_IFACES $IIFACE"
                 fi
             done
 
             # Break if the IFACE has been found
-            [ -z $FOUND_IFACE ] || break
+            if [ -n "$CARRIER_IFACES" ]; then
+                info "auto-detected$FOUND_IFACES"
+                break
+            fi
 
             [ $LOOP = 1 ] && info "waiting for link"
             [ $LOOP -gt 1 ] && echo -n "." >&3
@@ -94,17 +119,37 @@ start()
             LOOP=$(($LOOP + 1))
         done
 
-        bring_down_ifaces "$IFACES_BROUGHT_UP" "$FOUND_IFACE"
-
-        if [ -z "$FOUND_IFACE" ]; then
-            error "no cable detected on$IFACES_BROUGHT_UP"
+        if [ -z "$FOUND_IFACES" ]; then
+            error "no interfaces found"
             return 1
         fi
-        IFACE="$FOUND_IFACE"
+
+        if [ "$STATICIP" ]; then
+            IFACE="${CARRIER_IFACES# }"
+            # Leave only the first interface found
+            [ "$IFACE" = "${IFACE%% *}" ] || info "using ${IFACE%% *}"
+            IFACE="${IFACE%% *}"
+            bring_down_ifaces "$IFACES_BROUGHT_UP" "$IFACE"
+        else
+            IFACE="${FOUND_IFACES# }"
+        fi
+
+        if [ -z "$CARRIER_IFACES" ]; then
+            error "no carrier detected on$FOUND_IFACES"
+            [ "$STATICIP" ] && return 1
+        fi
+    fi
+
+    local NUM_IFACES=$(echo "$IFACE" | wc -w)
+
+    # Fail if interface explicitly requested by user does not exist
+    if [ $NUM_IFACES -eq 1 ] && [ ! -d "/sys/class/net/$IFACE" ]; then
+        info "missing $IFACE"
+        return 1
     fi
 
     # Wait for the network interface if it does not exist
-    if [ ! -d "/sys/class/net/$IFACE" -a -n "$TIMEOUT" ]; then
+    if [ $NUM_IFACES -eq 1 -a ! -d "/sys/class/net/$IFACE" -a -n "$TIMEOUT" ]; then
         info "waiting for $IFACE"
         local LOOP=0
         while [ $LOOP -lt $((TIMEOUT * 2)) ]; do
@@ -116,64 +161,75 @@ start()
     fi
 
     # Bring up networking
-    if [ -d "/sys/class/net/$IFACE" ]; then
-        logger -p 24.5 -t rc.net "Configuring $IFACE"
-        if [ "$STATICIP" ]; then
-            NETMASK=`echo "$STATICIP" | cut -f 2 -d '/'`
-            STATICIP=`echo "$STATICIP" | cut -f 1 -d '/'`
-            [ "$NETMASK" ] || STATICIP=""
-        fi
-        setup_wlan "$IFACE"
-        if [ "$STATICIP" ]; then
-            info "static IP $STATICIP"
-
-            # Set up IP
-            ifconfig "$IFACE" "$STATICIP" netmask "$NETMASK"
-            ifconfig "$IFACE" up
-
-            # Set up gateway
-            [ "$GATEWAY" ] && route add default gw "$GATEWAY"
-
-            # Set up DNS
-            if [ "$DNSDOMAIN" ]; then
-                [ -f /etc/resolv.conf ] && rm /etc/resolv.conf
-                touch /etc/resolv.conf
-                if [ "$DNSDOMAIN" ]; then
-                    echo "domain $DNSDOMAIN" >> /etc/resolv.conf
-                    echo "search $DNSDOMAIN" >> /etc/resolv.conf
-                fi
-                for DNSSERVER in $DNS; do
-                    echo "nameserver $DNSSERVER" >> /etc/resolv.conf
-                done
-            fi
-        else
-            info "DHCP"
-            [ -f /etc/resolv.conf ] && rm /etc/resolv.conf
-            ifconfig "$IFACE" up
-            [ "$BACKGROUND_UDHCPC" = "1" ] && UDHCPC_OPTIONS="-b $UDHCPC_OPTIONS"
-            /usr/bin/udhcpc -i "$IFACE" -s "/etc/udhcpc.scripts" $UDHCPC_OPTIONS
-        fi
-
-        # Store the interface name to file
-        echo "$IFACE" > "$SAVED_IFACE_FILE"
-    else
-        info "missing $IFACE"
-        return 1
+    logger -p 24.5 -t rc.net "Configuring $IFACE"
+    if [ "$STATICIP" ]; then
+        NETMASK=`echo "$STATICIP" | cut -f 2 -d '/'`
+        STATICIP=`echo "$STATICIP" | cut -f 1 -d '/'`
+        [ "$NETMASK" ] || STATICIP=""
     fi
+    setup_wlan "$IFACE"
+    if [ "$STATICIP" ]; then
+        info "static IP $STATICIP"
+
+        # Set up IP
+        ifconfig "$IFACE" "$STATICIP" netmask "$NETMASK"
+        ifconfig "$IFACE" up
+
+        # Set up gateway
+        [ "$GATEWAY" ] && route add default gw "$GATEWAY"
+
+        # Set up DNS
+        if [ "$DNSDOMAIN" ]; then
+            [ -f /etc/resolv.conf ] && rm /etc/resolv.conf
+            touch /etc/resolv.conf
+            if [ "$DNSDOMAIN" ]; then
+                echo "domain $DNSDOMAIN" >> /etc/resolv.conf
+                echo "search $DNSDOMAIN" >> /etc/resolv.conf
+            fi
+            for DNSSERVER in $DNS; do
+                echo "nameserver $DNSSERVER" >> /etc/resolv.conf
+            done
+        fi
+    else
+        info "DHCP on"
+        [ -f /etc/resolv.conf ] && rm /etc/resolv.conf
+        local IIFACE
+        for IIFACE in $IFACE; do
+            ifconfig "$IIFACE" up
+            if has_carrier "$IIFACE"; then
+                info "${IIFACE}*"
+                /usr/bin/udhcpc -i "$IIFACE" -s "/etc/udhcpc.scripts" $UDHCPC_OPTIONS >/dev/null 2>/dev/null
+            else
+                info "$IIFACE"
+                /usr/bin/start-stop-daemon --start --background --exec /usr/bin/udhcpc -- -i "$IIFACE" -s "/etc/udhcpc.scripts" $UDHCPC_OPTIONS
+            fi
+        done
+    fi
+
+    # Store the interface name to file
+    echo "$IFACE" > "$SAVED_IFACE_FILE"
 }
 
 stop()
 {
     # Read the interface that was started using start
-    [ ! -f /var/run/net.iface ] || IFACE="$(cat "$SAVED_IFACE_FILE")"
+    local ACTIVE_IFACES="$IFACE"
+    [ ! -f "$SAVED_IFACE_FILE" ] || ACTIVE_IFACES="$(cat "$SAVED_IFACE_FILE")"
+    [ "$ACTIVE_IFACES" ] || return 0
+    info "bringing down $ACTIVE_IFACES"
+
+    /usr/bin/start-stop-daemon --stop --exec /usr/bin/udhcpc
 
     # Bring down networking
-    if [ -d "/sys/class/net/$IFACE" ]; then
-        # Clear the IP address set, IFACE=auto mode shouldn't use the previous IP and return
-        # Sometimes the user may want to change the IP, so user may run restart
-        ifconfig "$IFACE" 0.0.0.0
-        ifconfig "$IFACE" down
-        /usr/bin/start-stop-daemon --stop --exec /usr/bin/udhcpc
-        true
-    fi
+    local IIFACE
+    for IIFACE in $ACTIVE_IFACES; do
+        if [ -d "/sys/class/net/$IIFACE" ]; then
+            # Clear the IP address set, IFACE=auto mode shouldn't use the previous IP and return
+            # Sometimes the user may want to change the IP, so user may run restart
+            ifconfig "$IIFACE" 0.0.0.0
+            ifconfig "$IIFACE" down
+        fi
+    done
+
+    rm -f "$SAVED_IFACE_FILE"
 }
