wait for eth device in net service
If the eth device is not immediately available after the kernel
finishes booting, wait for it.

Change-Id: I8268a1d765516b0b3376bf2cb68468a4459f498a
Reviewed-on: https://git-master.nvidia.com/r/1757121
Reviewed-by: Lael Jones <lajones@nvidia.com>
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Chris Dragan <kdragan@nvidia.com>
Tested-by: Chris Dragan <kdragan@nvidia.com>

diff --git a/scripts/etc/init.d/net b/scripts/etc/init.d/net
--- a/scripts/etc/init.d/net
+++ b/scripts/etc/init.d/net
@@ -22,6 +22,18 @@ done
 
 start()
 {
+    # Wait for the network interface if it does not exist
+    if [ ! -d "/sys/class/net/$IFACE" -a -n "$TIMEOUT" ]; then
+        echo -n " waiting for $IFACE" >&2
+        local LOOP=0
+        while [ $LOOP -lt $TIMEOUT ]; do
+            [ ! -d "/sys/class/net/$IFACE" ] || break
+            LOOP=$(($LOOP + 1))
+            sleep 1
+            echo -n "." >&2
+        done
+    fi
+
     # Bring up networking
     if [ -d "/sys/class/net/$IFACE" ]; then
         if [ "$STATICIP" ]; then
@@ -61,6 +73,9 @@ start()
                 /sbin/udhcpc -i "$IFACE" -s "/etc/udhcpc.scripts" $UDHCPC_OPTIONS
             fi
         fi
+    else
+        echo -n " missing $IFACE" >&2
+        return 1
     fi
 }
 
