update Tegra profile
- add libpcap
- disable broken version of strace
- work around glibc symlink on aarch64

Change-Id: Idcac9d1416113b98f8e03ab03d182123345fe8bd
Reviewed-on: http://git-master/r/757919
Reviewed-by: Automatic_Commit_Validation_User
Tested-by: Chris Dragan <kdragan@nvidia.com>
Reviewed-by: Lael Jones <lajones@nvidia.com>
Reviewed-by: Vivek Aseeja <vaseeja@nvidia.com>
Reviewed-by: Chris Dragan <kdragan@nvidia.com>

diff --git a/profiles/tegra/simrd/commands b/profiles/tegra/simrd/commands
--- a/profiles/tegra/simrd/commands
+++ b/profiles/tegra/simrd/commands
@@ -20,21 +20,23 @@ else
     MOUNTOPTS="udp,ro,vers=3,port=2049,mountport=2050,nolock,noacl,nordirplus"
 fi
 
-MODS_RUNSPACE="$MOUNTPOINT"
-[ "$RUNSPACE" ] && MODS_RUNSPACE="$MODS_RUNSPACE/$RUNSPACE"
-if mkdir -p "$MOUNTPOINT"; then
-    TRIES=10
-    while [ $TRIES -gt 0 ]; do
-        sleep 1
-        mount -t nfs -o "$MOUNTOPTS" "$NFSMOUNT" "$MOUNTPOINT" && break
-        TRIES=$(($TRIES-1))
-    done
-    if [ $TRIES -gt 0 ]; then
-        echo "export MODS_RUNSPACE=\"$MODS_RUNSPACE\"" >> /.bashrc
-        echo "export LD_LIBRARY_PATH=\"\$MODS_RUNSPACE\"" >> /.bashrc
+if ! echo "$MOUNTPOINT" | grep -q "^xxxx"; then
+    MODS_RUNSPACE="$MOUNTPOINT"
+    [ "$RUNSPACE" ] && MODS_RUNSPACE="$MODS_RUNSPACE/$RUNSPACE"
+    if mkdir -p "$MOUNTPOINT"; then
+        TRIES=10
+        while [ $TRIES -gt 0 ]; do
+            sleep 1
+            mount -t nfs -o "$MOUNTOPTS" "$NFSMOUNT" "$MOUNTPOINT" && break
+            TRIES=$(($TRIES-1))
+        done
+        if [ $TRIES -gt 0 ]; then
+            echo "export MODS_RUNSPACE=\"$MODS_RUNSPACE\"" >> /.bashrc
+            echo "export LD_LIBRARY_PATH=\"\$MODS_RUNSPACE\"" >> /.bashrc
+        else
+            echo "ERROR: Unable to mount $NFSMOUNT"
+        fi
     else
-        echo "ERROR: Unable to mount $NFSMOUNT"
+        echo "ERROR: Unable to create directory $MOUNTPOINT"
     fi
-else
-    echo "ERROR: Unable to create directory $MOUNTPOINT"
 fi
